services:
  wg-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: wireguard-web:latest
    container_name: wireguard-web
    ports:
      - "${APP_PORT:-3001}:4173"
    restart: unless-stopped
    networks:
      - wg-net

networks:
  wg-net:
    driver: bridge
