/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateWireguardRouteImport } from './routes/_private/wireguard'
import { Route as PrivateUsersRouteImport } from './routes/_private/users'
import { Route as PrivateWireguardStatsRouteImport } from './routes/_private/wireguard/stats'
import { Route as PrivateWireguardServersRouteImport } from './routes/_private/wireguard/servers'
import { Route as PrivateWireguardPeersRouteImport } from './routes/_private/wireguard/peers'
import { Route as PrivateUsersUserIdRouteImport } from './routes/_private/users/$userId'

const AuthSignUpLazyRouteImport = createFileRoute('/auth/signUp')()
const AuthSignInLazyRouteImport = createFileRoute('/auth/signIn')()
const AuthRecoveryPasswordLazyRouteImport = createFileRoute(
  '/auth/recovery-password',
)()
const PrivateSettingsLazyRouteImport = createFileRoute('/_private/settings')()
const PrivateProfileLazyRouteImport = createFileRoute('/_private/profile')()
const PrivateUsersIndexLazyRouteImport = createFileRoute('/_private/users/')()
const PrivateWireguardServersIndexLazyRouteImport = createFileRoute(
  '/_private/wireguard/servers/',
)()
const PrivateWireguardPeersIndexLazyRouteImport = createFileRoute(
  '/_private/wireguard/peers/',
)()
const PrivateWireguardServersServerIdLazyRouteImport = createFileRoute(
  '/_private/wireguard/servers/$serverId',
)()
const PrivateWireguardPeersPeerIdLazyRouteImport = createFileRoute(
  '/_private/wireguard/peers/$peerId',
)()

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/index.lazy').then((d) => d.Route),
)
const AuthSignUpLazyRoute = AuthSignUpLazyRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth/signUp.lazy').then((d) => d.Route))
const AuthSignInLazyRoute = AuthSignInLazyRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth/signIn.lazy').then((d) => d.Route))
const AuthRecoveryPasswordLazyRoute =
  AuthRecoveryPasswordLazyRouteImport.update({
    id: '/recovery-password',
    path: '/recovery-password',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/auth/recovery-password.lazy').then((d) => d.Route),
  )
const PrivateSettingsLazyRoute = PrivateSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/settings.lazy').then((d) => d.Route),
)
const PrivateProfileLazyRoute = PrivateProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/profile.lazy').then((d) => d.Route),
)
const PrivateWireguardRoute = PrivateWireguardRouteImport.update({
  id: '/wireguard',
  path: '/wireguard',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateUsersRoute = PrivateUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateUsersIndexLazyRoute = PrivateUsersIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateUsersRoute,
} as any).lazy(() =>
  import('./routes/_private/users/index.lazy').then((d) => d.Route),
)
const PrivateWireguardStatsRoute = PrivateWireguardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PrivateWireguardRoute,
} as any).lazy(() =>
  import('./routes/_private/wireguard/stats.lazy').then((d) => d.Route),
)
const PrivateWireguardServersRoute = PrivateWireguardServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => PrivateWireguardRoute,
} as any)
const PrivateWireguardPeersRoute = PrivateWireguardPeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => PrivateWireguardRoute,
} as any)
const PrivateUsersUserIdRoute = PrivateUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => PrivateUsersRoute,
} as any).lazy(() =>
  import('./routes/_private/users/$userId.lazy').then((d) => d.Route),
)
const PrivateWireguardServersIndexLazyRoute =
  PrivateWireguardServersIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateWireguardServersRoute,
  } as any).lazy(() =>
    import('./routes/_private/wireguard/servers/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateWireguardPeersIndexLazyRoute =
  PrivateWireguardPeersIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateWireguardPeersRoute,
  } as any).lazy(() =>
    import('./routes/_private/wireguard/peers/index.lazy').then((d) => d.Route),
  )
const PrivateWireguardServersServerIdLazyRoute =
  PrivateWireguardServersServerIdLazyRouteImport.update({
    id: '/$serverId',
    path: '/$serverId',
    getParentRoute: () => PrivateWireguardServersRoute,
  } as any).lazy(() =>
    import('./routes/_private/wireguard/servers/$serverId.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateWireguardPeersPeerIdLazyRoute =
  PrivateWireguardPeersPeerIdLazyRouteImport.update({
    id: '/$peerId',
    path: '/$peerId',
    getParentRoute: () => PrivateWireguardPeersRoute,
  } as any).lazy(() =>
    import('./routes/_private/wireguard/peers/$peerId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/ui': typeof UiRoute
  '/users': typeof PrivateUsersRouteWithChildren
  '/wireguard': typeof PrivateWireguardRouteWithChildren
  '/profile': typeof PrivateProfileLazyRoute
  '/settings': typeof PrivateSettingsLazyRoute
  '/auth/recovery-password': typeof AuthRecoveryPasswordLazyRoute
  '/auth/signIn': typeof AuthSignInLazyRoute
  '/auth/signUp': typeof AuthSignUpLazyRoute
  '/': typeof PrivateIndexRoute
  '/users/$userId': typeof PrivateUsersUserIdRoute
  '/wireguard/peers': typeof PrivateWireguardPeersRouteWithChildren
  '/wireguard/servers': typeof PrivateWireguardServersRouteWithChildren
  '/wireguard/stats': typeof PrivateWireguardStatsRoute
  '/users/': typeof PrivateUsersIndexLazyRoute
  '/wireguard/peers/$peerId': typeof PrivateWireguardPeersPeerIdLazyRoute
  '/wireguard/servers/$serverId': typeof PrivateWireguardServersServerIdLazyRoute
  '/wireguard/peers/': typeof PrivateWireguardPeersIndexLazyRoute
  '/wireguard/servers/': typeof PrivateWireguardServersIndexLazyRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/ui': typeof UiRoute
  '/wireguard': typeof PrivateWireguardRouteWithChildren
  '/profile': typeof PrivateProfileLazyRoute
  '/settings': typeof PrivateSettingsLazyRoute
  '/auth/recovery-password': typeof AuthRecoveryPasswordLazyRoute
  '/auth/signIn': typeof AuthSignInLazyRoute
  '/auth/signUp': typeof AuthSignUpLazyRoute
  '/': typeof PrivateIndexRoute
  '/users/$userId': typeof PrivateUsersUserIdRoute
  '/wireguard/stats': typeof PrivateWireguardStatsRoute
  '/users': typeof PrivateUsersIndexLazyRoute
  '/wireguard/peers/$peerId': typeof PrivateWireguardPeersPeerIdLazyRoute
  '/wireguard/servers/$serverId': typeof PrivateWireguardServersServerIdLazyRoute
  '/wireguard/peers': typeof PrivateWireguardPeersIndexLazyRoute
  '/wireguard/servers': typeof PrivateWireguardServersIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/ui': typeof UiRoute
  '/_private/users': typeof PrivateUsersRouteWithChildren
  '/_private/wireguard': typeof PrivateWireguardRouteWithChildren
  '/_private/profile': typeof PrivateProfileLazyRoute
  '/_private/settings': typeof PrivateSettingsLazyRoute
  '/auth/recovery-password': typeof AuthRecoveryPasswordLazyRoute
  '/auth/signIn': typeof AuthSignInLazyRoute
  '/auth/signUp': typeof AuthSignUpLazyRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/users/$userId': typeof PrivateUsersUserIdRoute
  '/_private/wireguard/peers': typeof PrivateWireguardPeersRouteWithChildren
  '/_private/wireguard/servers': typeof PrivateWireguardServersRouteWithChildren
  '/_private/wireguard/stats': typeof PrivateWireguardStatsRoute
  '/_private/users/': typeof PrivateUsersIndexLazyRoute
  '/_private/wireguard/peers/$peerId': typeof PrivateWireguardPeersPeerIdLazyRoute
  '/_private/wireguard/servers/$serverId': typeof PrivateWireguardServersServerIdLazyRoute
  '/_private/wireguard/peers/': typeof PrivateWireguardPeersIndexLazyRoute
  '/_private/wireguard/servers/': typeof PrivateWireguardServersIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/reset-password'
    | '/ui'
    | '/users'
    | '/wireguard'
    | '/profile'
    | '/settings'
    | '/auth/recovery-password'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/'
    | '/users/$userId'
    | '/wireguard/peers'
    | '/wireguard/servers'
    | '/wireguard/stats'
    | '/users/'
    | '/wireguard/peers/$peerId'
    | '/wireguard/servers/$serverId'
    | '/wireguard/peers/'
    | '/wireguard/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/ui'
    | '/wireguard'
    | '/profile'
    | '/settings'
    | '/auth/recovery-password'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/'
    | '/users/$userId'
    | '/wireguard/stats'
    | '/users'
    | '/wireguard/peers/$peerId'
    | '/wireguard/servers/$serverId'
    | '/wireguard/peers'
    | '/wireguard/servers'
  id:
    | '__root__'
    | '/_private'
    | '/auth'
    | '/reset-password'
    | '/ui'
    | '/_private/users'
    | '/_private/wireguard'
    | '/_private/profile'
    | '/_private/settings'
    | '/auth/recovery-password'
    | '/auth/signIn'
    | '/auth/signUp'
    | '/_private/'
    | '/_private/users/$userId'
    | '/_private/wireguard/peers'
    | '/_private/wireguard/servers'
    | '/_private/wireguard/stats'
    | '/_private/users/'
    | '/_private/wireguard/peers/$peerId'
    | '/_private/wireguard/servers/$serverId'
    | '/_private/wireguard/peers/'
    | '/_private/wireguard/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  UiRoute: typeof UiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/auth/signUp': {
      id: '/auth/signUp'
      path: '/signUp'
      fullPath: '/auth/signUp'
      preLoaderRoute: typeof AuthSignUpLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signIn': {
      id: '/auth/signIn'
      path: '/signIn'
      fullPath: '/auth/signIn'
      preLoaderRoute: typeof AuthSignInLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recovery-password': {
      id: '/auth/recovery-password'
      path: '/recovery-password'
      fullPath: '/auth/recovery-password'
      preLoaderRoute: typeof AuthRecoveryPasswordLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsLazyRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileLazyRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/wireguard': {
      id: '/_private/wireguard'
      path: '/wireguard'
      fullPath: '/wireguard'
      preLoaderRoute: typeof PrivateWireguardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/users': {
      id: '/_private/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof PrivateUsersIndexLazyRouteImport
      parentRoute: typeof PrivateUsersRoute
    }
    '/_private/wireguard/stats': {
      id: '/_private/wireguard/stats'
      path: '/stats'
      fullPath: '/wireguard/stats'
      preLoaderRoute: typeof PrivateWireguardStatsRouteImport
      parentRoute: typeof PrivateWireguardRoute
    }
    '/_private/wireguard/servers': {
      id: '/_private/wireguard/servers'
      path: '/servers'
      fullPath: '/wireguard/servers'
      preLoaderRoute: typeof PrivateWireguardServersRouteImport
      parentRoute: typeof PrivateWireguardRoute
    }
    '/_private/wireguard/peers': {
      id: '/_private/wireguard/peers'
      path: '/peers'
      fullPath: '/wireguard/peers'
      preLoaderRoute: typeof PrivateWireguardPeersRouteImport
      parentRoute: typeof PrivateWireguardRoute
    }
    '/_private/users/$userId': {
      id: '/_private/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof PrivateUsersUserIdRouteImport
      parentRoute: typeof PrivateUsersRoute
    }
    '/_private/wireguard/servers/': {
      id: '/_private/wireguard/servers/'
      path: '/'
      fullPath: '/wireguard/servers/'
      preLoaderRoute: typeof PrivateWireguardServersIndexLazyRouteImport
      parentRoute: typeof PrivateWireguardServersRoute
    }
    '/_private/wireguard/peers/': {
      id: '/_private/wireguard/peers/'
      path: '/'
      fullPath: '/wireguard/peers/'
      preLoaderRoute: typeof PrivateWireguardPeersIndexLazyRouteImport
      parentRoute: typeof PrivateWireguardPeersRoute
    }
    '/_private/wireguard/servers/$serverId': {
      id: '/_private/wireguard/servers/$serverId'
      path: '/$serverId'
      fullPath: '/wireguard/servers/$serverId'
      preLoaderRoute: typeof PrivateWireguardServersServerIdLazyRouteImport
      parentRoute: typeof PrivateWireguardServersRoute
    }
    '/_private/wireguard/peers/$peerId': {
      id: '/_private/wireguard/peers/$peerId'
      path: '/$peerId'
      fullPath: '/wireguard/peers/$peerId'
      preLoaderRoute: typeof PrivateWireguardPeersPeerIdLazyRouteImport
      parentRoute: typeof PrivateWireguardPeersRoute
    }
  }
}

interface PrivateUsersRouteChildren {
  PrivateUsersUserIdRoute: typeof PrivateUsersUserIdRoute
  PrivateUsersIndexLazyRoute: typeof PrivateUsersIndexLazyRoute
}

const PrivateUsersRouteChildren: PrivateUsersRouteChildren = {
  PrivateUsersUserIdRoute: PrivateUsersUserIdRoute,
  PrivateUsersIndexLazyRoute: PrivateUsersIndexLazyRoute,
}

const PrivateUsersRouteWithChildren = PrivateUsersRoute._addFileChildren(
  PrivateUsersRouteChildren,
)

interface PrivateWireguardPeersRouteChildren {
  PrivateWireguardPeersPeerIdLazyRoute: typeof PrivateWireguardPeersPeerIdLazyRoute
  PrivateWireguardPeersIndexLazyRoute: typeof PrivateWireguardPeersIndexLazyRoute
}

const PrivateWireguardPeersRouteChildren: PrivateWireguardPeersRouteChildren = {
  PrivateWireguardPeersPeerIdLazyRoute: PrivateWireguardPeersPeerIdLazyRoute,
  PrivateWireguardPeersIndexLazyRoute: PrivateWireguardPeersIndexLazyRoute,
}

const PrivateWireguardPeersRouteWithChildren =
  PrivateWireguardPeersRoute._addFileChildren(
    PrivateWireguardPeersRouteChildren,
  )

interface PrivateWireguardServersRouteChildren {
  PrivateWireguardServersServerIdLazyRoute: typeof PrivateWireguardServersServerIdLazyRoute
  PrivateWireguardServersIndexLazyRoute: typeof PrivateWireguardServersIndexLazyRoute
}

const PrivateWireguardServersRouteChildren: PrivateWireguardServersRouteChildren =
  {
    PrivateWireguardServersServerIdLazyRoute:
      PrivateWireguardServersServerIdLazyRoute,
    PrivateWireguardServersIndexLazyRoute:
      PrivateWireguardServersIndexLazyRoute,
  }

const PrivateWireguardServersRouteWithChildren =
  PrivateWireguardServersRoute._addFileChildren(
    PrivateWireguardServersRouteChildren,
  )

interface PrivateWireguardRouteChildren {
  PrivateWireguardPeersRoute: typeof PrivateWireguardPeersRouteWithChildren
  PrivateWireguardServersRoute: typeof PrivateWireguardServersRouteWithChildren
  PrivateWireguardStatsRoute: typeof PrivateWireguardStatsRoute
}

const PrivateWireguardRouteChildren: PrivateWireguardRouteChildren = {
  PrivateWireguardPeersRoute: PrivateWireguardPeersRouteWithChildren,
  PrivateWireguardServersRoute: PrivateWireguardServersRouteWithChildren,
  PrivateWireguardStatsRoute: PrivateWireguardStatsRoute,
}

const PrivateWireguardRouteWithChildren =
  PrivateWireguardRoute._addFileChildren(PrivateWireguardRouteChildren)

interface PrivateRouteChildren {
  PrivateUsersRoute: typeof PrivateUsersRouteWithChildren
  PrivateWireguardRoute: typeof PrivateWireguardRouteWithChildren
  PrivateProfileLazyRoute: typeof PrivateProfileLazyRoute
  PrivateSettingsLazyRoute: typeof PrivateSettingsLazyRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateUsersRoute: PrivateUsersRouteWithChildren,
  PrivateWireguardRoute: PrivateWireguardRouteWithChildren,
  PrivateProfileLazyRoute: PrivateProfileLazyRoute,
  PrivateSettingsLazyRoute: PrivateSettingsLazyRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface AuthRouteChildren {
  AuthRecoveryPasswordLazyRoute: typeof AuthRecoveryPasswordLazyRoute
  AuthSignInLazyRoute: typeof AuthSignInLazyRoute
  AuthSignUpLazyRoute: typeof AuthSignUpLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRecoveryPasswordLazyRoute: AuthRecoveryPasswordLazyRoute,
  AuthSignInLazyRoute: AuthSignInLazyRoute,
  AuthSignUpLazyRoute: AuthSignUpLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  UiRoute: UiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
