name: Deploy with Docker Compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REMOTE_HOST: 147.45.245.104

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts
        run: ssh-keyscan ${{ env.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: make deploy ssh
