name: Deploy with Docker Compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEPLOY_PATH: ./development/wireguard-web
  REMOTE_USER: root
  REMOTE_HOST: 147.45.245.104
  REMOTE_ADDRESS: ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts and Copy files via SCP
        run: |
          ssh-keyscan ${{ env.REMOTE_HOST }} >> ~/.ssh/known_hosts
          rsync -avz --delete --exclude-from='.gitignore' --rsync-path="mkdir -p ${{ env.DEPLOY_PATH }} && rsync" ./ ${{ env.REMOTE_ADDRESS }}:${{ env.DEPLOY_PATH }}

      - name: Run Docker Compose on remote server
        run: ssh ${{ env.REMOTE_ADDRESS }} 'cd ${{ env.DEPLOY_PATH }} && docker compose --env-file .env.production up -d --no-deps --build --force-recreate'
