name: Build with Docker Compose # Имя workflow

on: # Определение событий, которые запускают workflow
  push: # Запуск при пуше в репозиторий
    branches: [ master ] # Только для ветки master
  pull_request: # Запуск при создании pull request
    branches: [ master ] # Только для ветки master

jobs: # Определение задач (jobs) в рамках workflow
  build: # Имя задачи

    runs-on: ubuntu-latest # Указание используемой виртуальной машины

    steps: # Шаги, выполняемые в рамках задачи
      - name: Checkout code # Имя шага
        uses: actions/checkout@v2 # Использование действия для клонирования кода репозитория

      - name: Set up Docker Compose # Имя шага
        run: sudo apt-get install docker-compose # Установка Docker Compose

      - name: Build and run containers # Имя шага
        run: docker-compose --env-file .env.production up -d --no-deps --build # Сборка и запуск контейнеров в фоновом режиме
