name: Deploy with Docker Compose # Имя workflow

on: # Определение событий, которые запускают workflow
  push: # Запуск при пуше в репозиторий
    branches: [ master ] # Только для ветки master
  pull_request: # Запуск при создании pull request
    branches: [ master ] # Только для ветки master

jobs: # Определение задач (jobs) в рамках workflow
  deploy: # Имя задачи

    runs-on: ubuntu-latest # Указание используемой виртуальной машины

    steps: # Шаги, выполняемые в рамках задачи
      - name: Checkout code # Имя шага
        uses: actions/checkout@v2 # Использование действия для клонирования кода репозитория

      - name: Set up SSH # Настройка SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SCP # Копирование файлов через rsync
        run: rsync -avz --delete --exclude-from='.gitignore' ./ root@147.45.245.104:/development/wireguard-web

      - name: Run Docker Compose on remote server # Запуск Docker Compose на удаленном сервере
        run: ssh root@147.45.245.104 'cd /development/wireguard-web && docker-compose --env-file .env.production up -d --no-deps --build'
