name: Deploy with Docker Compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEPLOY_PATH: ./development/wireguard-web
  REMOTE_USER: root
  REMOTE_HOST: 147.45.245.104

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Install make
#        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Docker Compose on remote server using Makefile
        run: |
          export REMOTE_ADDRESS=${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}
          ssh $REMOTE_ADDRESS 'cd ${{ env.DEPLOY_PATH }} && make deploy'
